djexperience/service/urls.py
from django.conf.urls import include, url
from djexperience.service import views as s


protest_patterns = [
    url(r'^$', s.ProtestList.as_view(), name='protest_list'),
    url(r'^add/$', s.ProtestCreate.as_view(), name='protest_add'),
    url(r'^(?P<pk>\d+)/$', s.ProtestDetail.as_view(), name='protest_detail'),
    url(
        r'^ajax/load-typeservices$',
        s.load_typeservices,
        name='ajax_load_typeservices'
    ),
]


urlpatterns = [
    url(r'^protest/', include(protest_patterns)),
]

djexperience/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('djexperience.core.urls', namespace='core')),
    url(r'^bookstore/', include('djexperience.bookstore.urls', namespace='bookstore')),
    url(r'^company/', include('djexperience.company.urls', namespace='company')),
    url(r'^crm/', include('djexperience.crm.urls', namespace='crm')),
    url(r'^myemail/', include('djexperience.myemail.urls', namespace='myemail')),
    url(r'^product/', include('djexperience.product.urls', namespace='product')),
    url(r'^selling/', include('djexperience.selling.urls', namespace='selling')),
    url(r'^service/', include('djexperience.service.urls', namespace='service')),
    url(r'^admin/', admin.site.urls),
]

djexperience/service/models.py
from django.db import models
from django.shortcuts import resolve_url as r
from djexperience.core.models import TimeStampedModel


class Service(models.Model):
    ''' Serviço '''
    title = models.CharField('serviço', max_length=100, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
        verbose_name = 'serviço'
        verbose_name_plural = 'serviços'


class TypeService(models.Model):
    ''' Tipo de Serviço '''
    title = models.CharField('tipo', max_length=100, unique=True)
    service = models.ForeignKey(Service, verbose_name='serviço')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
        verbose_name = 'tipo de serviço'
        verbose_name_plural = 'tipos de serviços'


class Protest(TimeStampedModel):
    ''' Reclamação '''
    typeservice = models.ForeignKey(
        TypeService,
        verbose_name='tipo de serviço'
    )
    description = models.TextField('Descrição')

    def __str__(self):
        return 'Reclamação #{}'.format(self.pk)

    class Meta:
        ordering = ('pk',)
        verbose_name = 'reclamação'
        verbose_name_plural = 'reclamações'

    def get_absolute_url(self):
        return r('service:protest_detail', pk=self.pk)

djexperience/service/forms.py
from django import forms
from .models import Protest, Service, TypeService


class ProtestForm(forms.ModelForm):
    service = forms.ModelChoiceField(
        queryset=Service.objects.all(),
        label='Serviços',
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Protest
        fields = (
            'service',
            'typeservice',
            'description',
        )

    def __init__(self, *args, **kwargs):
        super(ProtestForm, self).__init__(*args, **kwargs)
        self.fields['typeservice'].queryset = TypeService.objects.none()

        if 'service' in self.data:
            try:
                service_id = int(self.data.get('service'))
                typeservice = TypeService.objects.filter(service_id=service_id)
                typeservice = typeservice.order_by('title')
                self.fields['typeservice'].queryset = typeservice
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            obj = self.instance.service.typeservice_set.order_by('title')
            self.fields['typeservice'].queryset = obj

djexperience/service/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView
from .models import Protest, TypeService
from .forms import ProtestForm


class ProtestList(ListView):
    model = Protest
    paginate_by = 10


class ProtestCreate(CreateView):
    model = Protest
    form_class = ProtestForm
    success_url = reverse_lazy('service:protest_list')


class ProtestDetail(DetailView):
    model = Protest


def load_typeservices(request):
    service_id = request.GET.get('service')
    typeservices = TypeService.objects.filter(service_id=service_id)
    typeservices = typeservices.order_by('title')
    kw = {'typeservices': typeservices}
    return render(request, 'service/_include_typeservice_list_options.html', kw)

djexperience/service/templates/service/_include_typeservice_list_options.html
<option value="">---------</option>
{% for typeservice in typeservices %}
  <option value="{{ typeservice.pk }}">{{ typeservice.title }}</option>
{% endfor %}

djexperience/service/templates/service/protest_form.html
{% extends "base_bootstrap.html" %}
{% load bootstrap %}

{% block content %}

  <form id="protestForm" 
        class="form-horizontal col-sm-6" 
        method="POST" 
        action="." 
        data-url="{% url 'service:ajax_load_typeservices' %}">
    <legend>Fazer reclamação</legend>
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}
    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
        <button type="submit" id="id_submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </form>

<script>
  $('#id_service').change(function() {
    let url = $('#protestForm').data('url')
    let serviceId = $(this).val()

    $.ajax({
      url: url,
      data: {
        'service': serviceId
      },
      success: function(data) {
        $('#id_typeservice').html(data);
      },
    });
  });
</script>

{% endblock content %}

djexperience/service/templates/service/protest_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <a href="{% url 'service:protest_add' %}" class="btb btn-sm btn-success">Fazer reclamação</a>
  {% if object_list %}
    <table class="table">
      <thead>
        <tr>
          <th>Reclamação</th>
          <th>Serviço</th>
          <th>Tipo de Serviço</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{ object }}</td>
            <td>{{ object.typeservice.service }}</td>
            <td>{{ object.typeservice }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="text-center alert alert-warning">Sem itens na lista. <a href="{% url 'service:protest_add' %}">Cadastrar</a></p>
  {% endif %}
{% endblock content %}