djexperience/crm/urls.py
from django.conf.urls import include, url
from djexperience.crm import views as c

employee_patterns = [
    url(r'^$', c.employee_list, name='employee_list'),
    url(r'^add/$', c.employee_create, name='employee_add'),
]

customer_patterns = [
    url(r'^$', c.CustomerList.as_view(), name='customer_list'),
    url(r'^json/$', c.customer_json, name='customer_json'),
    url(r'^json2/$', c.customer_list_by_json, name='customer_json2'),
    url(r'^render/$', c.customer_json_render, name='customer_json_render'),
    url(r'^(?P<slug>[\w-]+)/$', c.customer_detail, name='customer_detail'),
    url(r'^export/xls/$', c.export_users_xls, name='export_users_xls'),
]

provider_patterns = [
    url(r'^$', c.provider_list, name='provider_list'),
    url(r'^add/$', c.ProviderCreate.as_view(), name='provider_add'),
]

seller_patterns = [
    url(r'^$', c.seller_list, name='seller_list'),
]

urlpatterns = [
    url(r'^$', c.home, name='crm_index'),
    url(r'^employee/', include(employee_patterns)),
    url(r'^customer/', include(customer_patterns)),
    url(r'^provider/', include(provider_patterns)),
    url(r'^seller/', include(seller_patterns)),
]

djexperience/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('djexperience.core.urls', namespace='core')),
    url(r'^bookstore/', include('djexperience.bookstore.urls', namespace='bookstore')),
    url(r'^company/', include('djexperience.company.urls', namespace='company')),
    url(r'^crm/', include('djexperience.crm.urls', namespace='crm')),
    url(r'^myemail/', include('djexperience.myemail.urls', namespace='myemail')),
    url(r'^product/', include('djexperience.product.urls', namespace='product')),
    url(r'^selling/', include('djexperience.selling.urls', namespace='selling')),
    url(r'^service/', include('djexperience.service.urls', namespace='service')),
    url(r'^admin/', admin.site.urls),
]

djexperience/crm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import resolve_url as r
from djexperience.core.models import TimeStampedModel, Address
from djexperience.utils.lists import GENDER, TREATMENT, PHONE_TYPE
from djexperience.utils.lists import PERSON_TYPE, CUSTOMER_TYPE
from .managers import CustomerManager


class People(TimeStampedModel, Address):
    gender = models.CharField('gênero', max_length=1,
                              choices=GENDER, blank=True)
    treatment = models.CharField(
        'tratamento', max_length=4, choices=TREATMENT, blank=True)
    slug = models.SlugField('slug', blank=True)
    photo = models.URLField('foto', null=True, blank=True)
    birthday = models.DateTimeField('nascimento', null=True, blank=True)
    company = models.CharField('empresa', max_length=50, blank=True)
    department = models.CharField('departamento', max_length=50, blank=True)
    cpf = models.CharField('CPF', max_length=11,
                           unique=True, null=True, blank=True)
    rg = models.CharField('RG', max_length=11, blank=True)
    cnpj = models.CharField('CNPJ', max_length=14,
                            unique=True, null=True, blank=True)
    ie = models.CharField(u'inscrição estadual', max_length=12, blank=True)
    active = models.BooleanField('ativo', default=True)
    blocked = models.BooleanField('bloqueado', default=False)

    class Meta:
        abstract = True

    def __str__(self):
        return ' '.join(filter(None, [self.get_treatment_display(), self.first_name, self.last_name]))

    full_name = property(__str__)


class Person(People):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField('sobrenome', max_length=50, blank=True)
    email = models.EmailField(null=True, blank=True)
    occupation = models.ForeignKey(
        'Occupation', verbose_name='cargo', null=True, blank=True)
    person_type = models.CharField(
        'tipo de pessoa', max_length=1, choices=PERSON_TYPE, default='p')
    customer_type = models.CharField(
        'tipo de cliente', max_length=1, choices=CUSTOMER_TYPE, blank=True)

    class Meta:
        ordering = ['first_name']
        verbose_name = 'contato'
        verbose_name_plural = 'contatos'

    def __str__(self):
        return self.full_name


class PhonePerson(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    person = models.ForeignKey('Person')
    phone_type = models.CharField(
        'tipo', max_length=3, choices=PHONE_TYPE, default='pri')


class Customer(Person):
    objects = CustomerManager()

    class Meta:
        proxy = True
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def get_absolute_url(self):
        return r('crm:customer_detail', slug=self.slug)


class Employee(People, User):
    occupation = models.ForeignKey(
        'Occupation', verbose_name='cargo', null=True, blank=True)
    internal = models.BooleanField('interno', default=True)
    commissioned = models.BooleanField('comissionado', default=True)
    commission = models.DecimalField(
        'comissão', max_digits=6, decimal_places=2, default=0.01)
    date_release = models.DateTimeField('data de saída', null=True, blank=True)

    class Meta:
        ordering = ['username']
        verbose_name = 'funcionário'
        verbose_name_plural = 'funcionários'

    def __str__(self):
        return self.username


class PhoneEmployee(models.Model):
    phone = models.CharField('telefone', max_length=20, blank=True)
    employee = models.ForeignKey('Employee')
    phone_type = models.CharField(
        'tipo', max_length=3, choices=PHONE_TYPE, default='pri')


class Occupation(models.Model):
    occupation = models.CharField('cargo', max_length=50, unique=True)

    class Meta:
        ordering = ['occupation']
        verbose_name = 'cargo'
        verbose_name_plural = 'cargos'

    def __str__(self):
        return self.occupation


class SellerManager(models.Manager):

    def get_queryset(self):
        return super(SellerManager, self).get_queryset()\
            .filter(occupation__occupation='Vendedor')


class Provider(Person):
    type_product = models.ManyToManyField(
        'product.TypeProduct', verbose_name='tipo de produto')

    class Meta:
        ordering = ['first_name']
        verbose_name = 'fornecedor'
        verbose_name_plural = 'fornecedores'

    def __str__(self):
        return self.first_name


class Seller(Employee):
    objects = SellerManager()

    class Meta:
        proxy = True
        verbose_name = 'vendedor'
        verbose_name_plural = 'vendedores'

    def __str__(self):
        return self.username

djexperience/crm/forms.py
from django import forms
from djexperience.utils.lists import GENDER
from .models import Customer, Employee, Provider


class CustomerForm(forms.ModelForm):
    gender = forms.ChoiceField(
        label='Sexo', choices=GENDER, initial='M', widget=forms.RadioSelect)

    class Meta:
        model = Customer
        fields = ['gender', 'treatment', 'first_name', 'last_name', 'email',
                  'slug', 'photo', 'birthday', 'occupation', 'company',
                  'department', 'cpf', 'rg', 'cnpj', 'ie',
                  'address', 'complement', 'district', 'city', 'uf', 'cep',
                  'customer_type', 'active', 'blocked']

    def clean_cpf(self):
        return self.cleaned_data['cpf'] or None

    def clean_cnpj(self):
        return self.cleaned_data['cnpj'] or None


class EmployeeForm(forms.ModelForm):
    password = forms.CharField(label='Senha', widget=forms.PasswordInput)

    class Meta:
        model = Employee
        fields = ['username', 'email', 'password']

    def clean_cpf(self):
        return self.cleaned_data['cpf'] or None


class ProviderForm(forms.ModelForm):
    gender = forms.ChoiceField(
        label='Sexo', choices=GENDER, initial='M', widget=forms.RadioSelect)

    class Meta:
        model = Provider
        fields = '__all__'

djexperience/crm/views.py
import json
import xlwt
from datetime import date, datetime
from django.http import HttpResponse
from django.shortcuts import render
from django.core import serializers
from django.views.generic import CreateView, ListView, DetailView
from .models import Employee, Provider, Customer, Seller
from .forms import EmployeeForm, ProviderForm


def home(request):
    return render(request, 'crm_index.html')


employee_list = ListView.as_view(model=Employee)


def employee_create(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            e = form.save(commit=False)
            e.slug = e.username
            e.is_staff = True
            e.set_password(form.cleaned_data['password'])
            e.save()
            return render(request, 'index.html')
    else:
        form = EmployeeForm()
    return render(request, 'crm/employee_form.html', {'form': form})


class CustomerList(ListView):
    model = Customer


customer_detail = DetailView.as_view(model=Customer)


def customer_json(request):
    customers = Customer.objects.all()
    json = serializers.serialize('json', customers)
    return HttpResponse(json, content_type='application/json')


def customer_list_by_json(request):
    customers = Customer.objects.all()
    data_as_json = serializers.serialize('json', customers)
    data_as_dict = json.loads(data_as_json)
    data_as_dict = {'mydict': data_as_dict}
    return render(request, 'crm/customer_json2.html', context=data_as_dict)


def customer_json_render(request):
    return render(request, 'crm/customer_json.html')


def export_users_xls(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="customers.xls"'

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('Customers')

    # Sheet header, first row
    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    columns = ['Nome', 'Sobrenome', 'E-mail', 'Nascimento', 'Criado em']

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # Sheet body, remaining rows
    default_style = xlwt.XFStyle()

    rows = Customer.objects.all().values_list('first_name',
                                              'last_name',
                                              'email',
                                              'birthday',
                                              'created')
    for row, rowdata in enumerate(rows):
        row_num += 1
        for col, val in enumerate(rowdata):
            if isinstance(val, datetime):
                val = val.strftime('%d/%m/%Y %H:%M')
            elif isinstance(val, date):
                val = val.strftime('%d/%m/%Y')
            ws.write(row_num, col, val, default_style)

    wb.save(response)
    return response


class ProviderCreate(CreateView):
    model = Provider
    form_class = ProviderForm


provider_list = ListView.as_view(model=Provider)

seller_list = ListView.as_view(model=Seller)

djexperience/crm/templates/crm/customer_detail.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
  <title>Customer Detail</title>
{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- edit -->
    <a href="{ url 'crm:customer_edit' customer.slug %}">
        <button id="edit_customer" type="button" class="btn btn-success">
            <span class="fa fa-pencil"></span> Editar
        </button>
    </a>
</form>

<div class="col-lg-8">
  <div class="col-md-offset-3 column">
    <h1>{{ object.full_name }}</h1>
    {% if object.email %}
      <h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
    {% endif %}
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
      {% if object.type_custom == 'p' %}
        <tr>
          <th class="col-md-3 text-right">Gênero</th>
          <td>{{ object.get_gender_display }}</td>
        </tr>
      {% endif %}
      {% if object.company %}
        <tr>
          <th class="col-md-3 text-right">Empresa</th>
          <td>{{ object.company }}</td>
        </tr>
      {% endif %}
      {% if object.department %}
        <tr>
          <th class="col-md-3 text-right">Departamento</th>
          <td>{{ object.department }}</td>
        </tr>
      {% endif %}
      {% if object.phone1 %}
        <tr>
          <th class="col-md-3 text-right">Telefone 1</th>
          <td>{{ object.phone1 }}</td>
        </tr>
      {% else %}
        <tr>
          <th class="col-md-3 text-right">Telefone 1</th>
          <td>---</td>
        </tr>
      {% endif %}
      {% if object.phone2 %}
        <tr>
          <th class="col-md-3 text-right">Telefone 2</th>
          <td>{{ object.phone2 }}</td>
        </tr>
      {% endif %}
      {% if object.phone3 %}
        <tr>
          <th class="col-md-3 text-right">Telefone 3</th>
          <td>{{ object.phone3 }}</td>
        </tr>
      {% endif %}
      {% if object.cpf %}
        <tr>
          <th class="col-md-3 text-right">CPF</th>
          <td>{{ object.cpf }}</td>
        </tr>
      {% endif %}
      {% if object.rg %}
        <tr>
          <th class="col-md-3 text-right">RG</th>
          <td>{{ object.rg }}</td>
        </tr>
      {% endif %}
      {% if object.cnpj %}
        <tr>
          <th class="col-md-3 text-right">CNPJ</th>
          <td>{{ object.cnpj }}</td>
        </tr>
      {% endif %}
      {% if object.ie %}
        <tr>
          <th class="col-md-3 text-right">IE</th>
          <td>{{ object.ie }}</td>
        </tr>
      {% endif %}
      <tr>
        <th class="col-md-3 text-right">Ativo</th>
          <td><span class="glyphicon {{ object.active|yesno:'glyphicon-ok-sign ok,glyphicon-minus-sign no'}}"></span></td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Bloqueado</th>
          <td><span class="glyphicon {{ object.blocked|yesno:'glyphicon-ok-sign ok,glyphicon-minus-sign no'}}"></span></td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Tipo de cliente</th>
        <td>{{ object.get_customer_type_display }}</td>
      </tr>

      {% if object.address %}
        <tr>
          <th class="col-md-3 text-right">Endereço</th>
          <td>{{ object.address }}</td>
        </tr>
      {% endif %}
      {% if object.complement %}
        <tr>
          <th class="col-md-3 text-right">Complemento</th>
          <td>{{ object.complement }}</td>
        </tr>
      {% endif %}
      {% if object.district %}
        <tr>
          <th class="col-md-3 text-right">Bairro</th>
          <td>{{ object.district }}</td>
        </tr>
      {% endif %}
      {% if object.city %}
        <tr>
          <th class="col-md-3 text-right">Cidade</th>
          <td>{{ object.city }}</td>
        </tr>
      {% endif %}
      {% if object.uf %}
        <tr>
          <th class="col-md-3 text-right">UF</th>
          <td>{{ object.uf }}</td>
        </tr>
      {% endif %}
      {% if object.cep %}
        <tr>
          <th class="col-md-3 text-right">CEP</th>
          <td>{{ object.cep }}</td>
        </tr>
      {% endif %}

    </tbody>
  </table>
</div>

{% endblock content %}

djexperience/crm/templates/crm/customer_json.html
{% extends "base_crm_list.html" %}
{% load static %}

{% block title %}
  <title>CRM|Customer</title>
{% endblock title %}

{% block content %}

<div class="ui main text container">
    <h1 class="ui header">Clientes</h1>
    <p>Gerencie seus clientes.</p>

  <table class="ui celled table" id="example">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>
</div>

<script type="text/javascript" class="init">
  $(document).ready(function() {
    $('#example').dataTable( {
      "processing": true,
      "ajax": {
        "processing": true,
        "url": "{% url 'crm:customer_json' %}",
        "dataSrc": ""
      },
      "columns": [
        { "data": "fields.first_name" },
        { "data": "fields.email" },
      ]
    });
  });
</script>

{% endblock content %}

djexperience/crm/templates/crm/customer_json2.html
{% extends "base_crm_list.html" %}
{% load static %}

{% block title %}
  <title>CRM|Customer</title>
{% endblock title %}

{% block content %}

  <div class="ui main text container">
    <h1 class="ui header">Clientes</h1>
    <p>Gerencie seus clientes.</p>

{% if data_as_dict %}
  <table class="ui celled table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
      </tr>
    </thead>
    <tbody>
      {% for item in data_as_dict %}
        <tr>
          <td>{{ item.first_name }}</td>
          <td>{{ item.email|default:'---' }}</td>
        </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr><th colspan="4">
        <div class="ui right floated pagination menu">
          <a class="icon item">
            <i class="left chevron icon"></i>
          </a>
          <a class="item">1</a>
          <a class="item">2</a>
          <a class="item">3</a>
          <a class="item">4</a>
          <a class="icon item">
            <i class="right chevron icon"></i>
          </a>
        </div>
      </th>
    </tr></tfoot>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

  </div>

{% endblock content %}

djexperience/crm/templates/crm/customer_list.html
{% extends "base_crm_list.html" %}
{% load static %}

{% block title %}
  <title>CRM|Customer</title>
{% endblock title %}

{% block content %}

  <div class="ui main text container">
    <h1 class="ui header">Clientes</h1>
    <p>Gerencie seus clientes. - <a href="{% url 'crm:export_users_xls' %}">Exportar Excel</a></p>

{% if object_list %}
  <table class="ui celled table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Foto</th>
        <th>E-mail</th>
        <th>Tipo de Cliente</th>
      </tr>
    </thead>
    <tbody>
      {% for item in object_list %}
        <tr>
          <td>{{ item.full_name }}</td>
          <td><img src="{{ item.photo|default:'http://lorempixel.com/100/100/people/' }}" class="img-square" style="height: 30px;" /></td>
          <td>{{ item.email|default:'---' }}</td>
          <td>{{ item.get_customer_type_display|default:'---' }}</td>
        </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr><th colspan="4">
        <div class="ui right floated pagination menu">
          <a class="icon item">
            <i class="left chevron icon"></i>
          </a>
          <a class="item">1</a>
          <a class="item">2</a>
          <a class="item">3</a>
          <a class="item">4</a>
          <a class="icon item">
            <i class="right chevron icon"></i>
          </a>
        </div>
      </th>
    </tr></tfoot>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}

  </div>

{% endblock content %}

djexperience/crm/templates/crm/employee_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Registration{% endblock title %}
{% block content %}

<div class="page-header">
  <h2>Cadastre-se</h2>
</div>

<form class="form-horizontal" action="." method="POST">
  {% csrf_token %}
  <ul class="errorlist nonfield"></ul>
  {{ form.non_fields_errors }}
  <div class="form-group">
    <label class="control-label col-sm-2 col-lg-2">
      {{ form.username.label }}
    </label>
    <div class="col-sm-4 col-lg-4">
      {{ form.username|attr:"class:form-control" }} {{ form.username.errors }}
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2 col-lg-2">
      {{ form.email.label }}
    </label>
    <div class="col-sm-4 col-lg-4">
      {{ form.email|attr:"class:form-control" }} {{ form.email.errors }}
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2 col-lg-2">
      {{ form.password.label }}
    </label>
    <div class="col-sm-4 col-lg-4 controls">
      {{ form.password|attr:"class:form-control" }} {{ form.password.errors }}
    </div>
  </div>

  <div class="form-group">
      <div class="col-sm-2 col-sm-offset-2">
        <button type="submit" class="btn btn-primary">Cadastrar-se</button>
      </div>
    </div>
</form>

{% endblock content %}

djexperience/crm/templates/crm/employee_list.html
{% extends "base_crm_list.html" %}
{% load static %}

{% block title %}
  <title>CRM|Employee</title>
{% endblock title %}

{% block content %}

  <div class="ui main text container">
    <h1 class="ui header">Funcionários</h1>
    <p>Gerencie seus funcionários.</p>

    <table class="ui very basic collapsing celled table">
      <thead>
        <tr><th>Funcionário</th>
        <th>Cargo</th>
      </tr></thead>
      <tbody>
        {% for item in object_list %}
          <tr>
            <td>
              <h4 class="ui image header">
                <img src="{{ item.photo|default:'http://semantic-ui.com/images/avatar2/small/matthew.png' }}" class="ui mini rounded image">
                <div class="content">
                  {{ item.full_name }}
                  <div class="sub header">{{ item.email|default:'---' }}
                </div>
              </div>
            </h4></td>
            <td>
              {{ item.occupation|default:'---' }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>

{% endblock content %}

djexperience/crm/templates/crm/provider_form.html
{% extends "base_bookstore.html" %}
{% load bootstrap %}

{% block content %}

  <form class="form-horizontal col-sm-6" method="POST" action=".">
    <legend>Cadastrar fornecedor</legend>
    {% csrf_token %}
    {{ form.gender|bootstrap_horizontal }}
    {{ form.treatment|bootstrap_horizontal }}
    {{ form.first_name|bootstrap_horizontal }}
    {{ form.last_name|bootstrap_horizontal }}
    {{ form.email|bootstrap_horizontal }}
    {{ form.slug|bootstrap_horizontal }}
    {{ form.photo|bootstrap_horizontal }}
    {{ form.birthday|bootstrap_horizontal }}
    {{ form.occupation|bootstrap_horizontal }}
    {{ form.company|bootstrap_horizontal }}
    {{ form.department|bootstrap_horizontal }}
    {{ form.cpf|bootstrap_horizontal }}
    {{ form.rg|bootstrap_horizontal }}
    {{ form.cnpj|bootstrap_horizontal }}
    {{ form.ie|bootstrap_horizontal }}
    {{ form.address|bootstrap_horizontal }}
    {{ form.complement|bootstrap_horizontal }}
    {{ form.district|bootstrap_horizontal }}
    {{ form.city|bootstrap_horizontal }}
    {{ form.uf|bootstrap_horizontal }}
    {{ form.cep|bootstrap_horizontal }}
    <div class="form-group">
      <div class="col-sm-10 col-sm-offset-2">
        <button type="submit" id="id_submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
  </form>

{% endblock content %}

djexperience/crm/templates/crm/provider_list.html
{% extends "base_crm_list.html" %}
{% load static %}

{% block title %}
  <title>CRM|Provider</title>
{% endblock title %}

{% block content %}

  <div class="ui main text container">
    <h1 class="ui header">Fornecedores</h1>
    <p>Gerencie seus fornecedores.</p>

    <table class="ui celled table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Foto</th>
          <th>E-mail</th>
          <th>Tipo de Produto</th>
        </tr>
      </thead>
      <tbody>
        {% for item in object_list %}
          <tr>
            <td>{{ item.full_name }}</td>
            <td><img src="{{ item.photo|default:'https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png' }}" class="img-square" style="height: 30px;" /></td>
            <td>{{ item.email|default:'---' }}</td>
            <td>{{ item.type_product.all|join:', ' }}</td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr><th colspan="4">
          <div class="ui right floated pagination menu">
            <a class="icon item">
              <i class="left chevron icon"></i>
            </a>
            <a class="item">1</a>
            <a class="item">2</a>
            <a class="item">3</a>
            <a class="item">4</a>
            <a class="icon item">
              <i class="right chevron icon"></i>
            </a>
          </div>
        </th>
      </tr></tfoot>
    </table>

  </div>

{% endblock content %}

djexperience/crm/templates/crm/seller_list.html
{% extends "base_crm_list.html" %}
{% load static %}
{% load active_tags %}

{% block title %}
  <title>CRM|Seller</title>
{% endblock title %}

{% block content %}

  <div class="ui main text container">
    <h1 class="ui header">Vendedores</h1>
    <p>Gerencie seus vendedores.</p>

    <table class="ui very basic collapsing celled table">
      <thead>
        <tr><th>Funcionário</th>
        <th>Interno</th>
      </tr></thead>
      <tbody>
        {% for item in object_list %}
          <tr>
            <td>
              <h4 class="ui image header">
                <img src="{{ item.photo|default:'http://semantic-ui.com/images/avatar2/small/matthew.png' }}" class="ui mini rounded image">
                <div class="content">
                  {{ item.full_name }}
                  <div class="sub header">{{ item.email|default:'---' }}
                </div>
              </div>
            </h4></td>
            <td>
              {{ item.internal|active_tag }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>

{% endblock content %}