djexperience/bookstore/urls.py
from django.conf.urls import include, url
from djexperience.bookstore import views as b

customer_patterns = [
    url(r'^$', b.customer_list, name='customer_list'),
    url(r'^(?P<pk>\d+)/$', b.customer_detail, name='customer_detail'),
    url(r'^add/$', b.customer_form, name='customer_add'),
    url(r'^export/(.*)', b.export_data, name="export")
]

author_patterns = [
    url(r'^$', b.author_list, name='author_list'),
    url(r'^(?P<pk>\d+)/$', b.author_detail, name='author_detail'),
    url(r'^add/$', b.author_create, name='author_add'),
]

book_patterns = [
    url(r'^$', b.BookList.as_view(), name='book_list'),
    url(r'^(?P<pk>\d+)/$', b.BookDetail.as_view(), name='book_detail'),
    url(r'^(?P<pk>\d+)/edit/$', b.BookUpdate.as_view(), name='book_edit'),
    url(r'^add/$', b.BookCreate.as_view(), name='book_add'),
]

urlpatterns = [
    url(r'^$', b.home, name='bookstore_index'),
    url(r'^author/', include(author_patterns)),
    url(r'^customer/', include(customer_patterns)),
    url(r'^book/', include(book_patterns)),
]

djexperience/company/urls.py
from django.conf.urls import include, url
from djexperience.company import views as co
from djexperience.company import exports as exp

company_patterns = [
    url(r'^$', co.company_list, name='company_list'),
    url(r'^export/$', exp.export_data_contact, name='export_data_contact'),
]

urlpatterns = [
    url(r'^company/', include(company_patterns)),
]

djexperience/core/urls.py
from django.conf.urls import url
from djexperience.core.views import home, about


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
]

djexperience/crm/urls.py
from django.conf.urls import include, url
from djexperience.crm import views as c

employee_patterns = [
    url(r'^$', c.employee_list, name='employee_list'),
    url(r'^add/$', c.employee_create, name='employee_add'),
]

customer_patterns = [
    url(r'^$', c.CustomerList.as_view(), name='customer_list'),
    url(r'^json/$', c.customer_json, name='customer_json'),
    url(r'^json2/$', c.customer_list_by_json, name='customer_json2'),
    url(r'^render/$', c.customer_json_render, name='customer_json_render'),
    url(r'^(?P<slug>[\w-]+)/$', c.customer_detail, name='customer_detail'),
    url(r'^export/xls/$', c.export_users_xls, name='export_users_xls'),
]

provider_patterns = [
    url(r'^$', c.provider_list, name='provider_list'),
    url(r'^add/$', c.ProviderCreate.as_view(), name='provider_add'),
]

seller_patterns = [
    url(r'^$', c.seller_list, name='seller_list'),
]

urlpatterns = [
    url(r'^$', c.home, name='crm_index'),
    url(r'^employee/', include(employee_patterns)),
    url(r'^customer/', include(customer_patterns)),
    url(r'^provider/', include(provider_patterns)),
    url(r'^seller/', include(seller_patterns)),
]

djexperience/service/urls.py
from django.conf.urls import include, url
from djexperience.service import views as s


protest_patterns = [
    url(r'^$', s.ProtestList.as_view(), name='protest_list'),
    url(r'^add/$', s.ProtestCreate.as_view(), name='protest_add'),
    url(r'^(?P<pk>\d+)/$', s.ProtestDetail.as_view(), name='protest_detail'),
    url(
        r'^ajax/load-typeservices$',
        s.load_typeservices,
        name='ajax_load_typeservices'
    ),
]


urlpatterns = [
    url(r'^protest/', include(protest_patterns)),
]

djexperience/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('djexperience.core.urls', namespace='core')),
    url(r'^bookstore/', include('djexperience.bookstore.urls', namespace='bookstore')),
    url(r'^company/', include('djexperience.company.urls', namespace='company')),
    url(r'^crm/', include('djexperience.crm.urls', namespace='crm')),
    url(r'^myemail/', include('djexperience.myemail.urls', namespace='myemail')),
    url(r'^product/', include('djexperience.product.urls', namespace='product')),
    url(r'^selling/', include('djexperience.selling.urls', namespace='selling')),
    url(r'^service/', include('djexperience.service.urls', namespace='service')),
    url(r'^admin/', admin.site.urls),
]

djexperience/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField('endereço', max_length=100, blank=True)
    complement = models.CharField('complemento', max_length=100, blank=True)
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField('UF', max_length=2,
                          choices=STATE_CHOICES, blank=True)
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True

djexperience/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'core/about.html')

djexperience/core/templates/includes/nav.html
{% load activeurl %}

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Django Experience</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          {% activeurl %}
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="{% url 'company:company_list' %}">Empresa</a>
                </li>
                <li>
                    <a class="page-scroll" href="{% url 'service:protest_list' %}">Reclamações</a>
                </li>
                <li>
                    <a class="page-scroll" href="#about">Sobre</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Serviços</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Portfólio</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contato</a>
                </li>
            </ul>
          {% endactiveurl %}
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

djexperience/core/templates/includes/nav_bookstore.html
{% load static %}
<div class="android-header mdl-layout__header mdl-layout__header--waterfall">
  <div class="mdl-layout__header-row">
          <span class="android-title mdl-layout-title">
            <a href="{% url 'bookstore:bookstore_index' %}"><img class="android-logo-image" src="{% static "img/django-logo-experience.png" %}"></a>
          </span>
    <!-- Add spacer, to align navigation to the right in desktop -->
    <div class="android-header-spacer mdl-layout-spacer"></div>
    <div class="android-search-box mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right mdl-textfield--full-width">
      <label class="mdl-button mdl-js-button mdl-button--icon" for="search-field">
        <i class="material-icons">search</i>
      </label>
      <div class="mdl-textfield__expandable-holder">
        <input class="mdl-textfield__input" type="text" id="search-field">
      </div>
    </div>
    <!-- Navigation -->
    <div class="android-navigation-container">
      <nav class="android-navigation mdl-navigation">
        <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'bookstore:book_list' %}">Livros</a>
        <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'bookstore:author_list' %}">Autores</a>
        <a class="mdl-navigation__link mdl-typography--text-uppercase" href="{% url 'bookstore:customer_list' %}">Clientes</a>
      </nav>
    </div>
    <span class="android-mobile-title mdl-layout-title">
            <a href="{% url 'bookstore:bookstore_index' %}"><img class="android-logo-image" src="{% static "img/django-logo-experience.png" %}"></a>
          </span>
    <button class="android-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
      <i class="material-icons">more_vert</i>
    </button>
    <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="more-button">
      <li class="mdl-menu__item">5.0 Lollipop</li>
      <li class="mdl-menu__item">4.4 KitKat</li>
      <li disabled class="mdl-menu__item">4.3 Jelly Bean</li>
      <li class="mdl-menu__item">Android History</li>
    </ul>
  </div>
</div>

<div class="android-drawer mdl-layout__drawer">
        <span class="mdl-layout-title">
          <a href="{% url 'bookstore:bookstore_index' %}"><img class="android-logo-image" src="{% static "img/django-logo-experience.png" %}"></a>
        </span>
  <nav class="mdl-navigation">
    <a class="mdl-navigation__link" href="{% url 'bookstore:book_list' %}">Livros</a>
    <a class="mdl-navigation__link" href="{% url 'bookstore:customer_list' %}">Clientes</a>
    <div class="android-drawer-separator"></div>
    <span class="mdl-navigation__link" href="">Versions</span>
    <a class="mdl-navigation__link" href="">Lollipop 5.0</a>
    <a class="mdl-navigation__link" href="">KitKat 4.4</a>
    <a class="mdl-navigation__link" href="">Jelly Bean 4.3</a>
    <a class="mdl-navigation__link" href="">Android history</a>
    <div class="android-drawer-separator"></div>
    <span class="mdl-navigation__link" href="">For developers</span>
    <a class="mdl-navigation__link" href="">App developer resources</a>
    <a class="mdl-navigation__link" href="">Android Open Source Project</a>
    <a class="mdl-navigation__link" href="">Android SDK</a>
  </nav>
</div>

djexperience/core/templates/includes/pagination.html
<!-- pagination -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}">&laquo;</a></li>
      {% endif %}
      {% for pg in page_obj.paginator.page_range %}
        {% if page_obj.number == pg %}
          <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
        {% else %}
          <li><a href="?page={{ pg }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}">{{ pg }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}&search_box={{ request.GET.search_box }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>

<!-- https://www.technovelty.org/web/skipping-pages-with-djangocorepaginator.html -->