djexperience/bookstore/urls.py
from django.conf.urls import include, url
from djexperience.bookstore import views as b

customer_patterns = [
    url(r'^$', b.customer_list, name='customer_list'),
    url(r'^(?P<pk>\d+)/$', b.customer_detail, name='customer_detail'),
    url(r'^add/$', b.customer_form, name='customer_add'),
    url(r'^export/(.*)', b.export_data, name="export")
]

author_patterns = [
    url(r'^$', b.author_list, name='author_list'),
    url(r'^(?P<pk>\d+)/$', b.author_detail, name='author_detail'),
    url(r'^add/$', b.author_create, name='author_add'),
]

book_patterns = [
    url(r'^$', b.BookList.as_view(), name='book_list'),
    url(r'^(?P<pk>\d+)/$', b.BookDetail.as_view(), name='book_detail'),
    url(r'^(?P<pk>\d+)/edit/$', b.BookUpdate.as_view(), name='book_edit'),
    url(r'^add/$', b.BookCreate.as_view(), name='book_add'),
]

urlpatterns = [
    url(r'^$', b.home, name='bookstore_index'),
    url(r'^author/', include(author_patterns)),
    url(r'^customer/', include(customer_patterns)),
    url(r'^book/', include(book_patterns)),
]

djexperience/core/urls.py
from django.conf.urls import url
from djexperience.core.views import home, about


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
]

djexperience/crm/urls.py
from django.conf.urls import include, url
from djexperience.crm import views as c

employee_patterns = [
    url(r'^$', c.employee_list, name='employee_list'),
    url(r'^add/$', c.employee_create, name='employee_add'),
]

customer_patterns = [
    url(r'^$', c.CustomerList.as_view(), name='customer_list'),
    url(r'^json/$', c.customer_json, name='customer_json'),
    url(r'^json2/$', c.customer_list_by_json, name='customer_json2'),
    url(r'^render/$', c.customer_json_render, name='customer_json_render'),
    url(r'^(?P<slug>[\w-]+)/$', c.customer_detail, name='customer_detail'),
    url(r'^export/xls/$', c.export_users_xls, name='export_users_xls'),
]

provider_patterns = [
    url(r'^$', c.provider_list, name='provider_list'),
    url(r'^add/$', c.ProviderCreate.as_view(), name='provider_add'),
]

seller_patterns = [
    url(r'^$', c.seller_list, name='seller_list'),
]

urlpatterns = [
    url(r'^$', c.home, name='crm_index'),
    url(r'^employee/', include(employee_patterns)),
    url(r'^customer/', include(customer_patterns)),
    url(r'^provider/', include(provider_patterns)),
    url(r'^seller/', include(seller_patterns)),
]

djexperience/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('djexperience.core.urls', namespace='core')),
    url(r'^bookstore/', include('djexperience.bookstore.urls', namespace='bookstore')),
    url(r'^company/', include('djexperience.company.urls', namespace='company')),
    url(r'^crm/', include('djexperience.crm.urls', namespace='crm')),
    url(r'^myemail/', include('djexperience.myemail.urls', namespace='myemail')),
    url(r'^product/', include('djexperience.product.urls', namespace='product')),
    url(r'^selling/', include('djexperience.selling.urls', namespace='selling')),
    url(r'^service/', include('djexperience.service.urls', namespace='service')),
    url(r'^admin/', admin.site.urls),
]

djexperience/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField('endereço', max_length=100, blank=True)
    complement = models.CharField('complemento', max_length=100, blank=True)
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField('UF', max_length=2,
                          choices=STATE_CHOICES, blank=True)
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True

djexperience/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'core/about.html')

djexperience/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Django Experience{% endblock title %}</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static "css/animate.min.css" %}" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static "css/creative.css" %}" type="text/css">
    <!-- django_tables2 css -->
    <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}">
    <!-- dataTables css -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- dataTables -->
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block css %}{% endblock css %}

</head>

<body id="page-top">

    {% include "includes/nav.html" %}

    {% block content %}
        
    {% endblock content %}


    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <script src="{% static "js/jquery.fittext.js" %}"></script>
    <script src="{% static "js/wow.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/creative.js" %}"></script>

    <!-- dataTables.min.js -->
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

    {% block js %}{% endblock js %}
</body>

</html>

djexperience/core/templates/base_bookstore.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Django Experience | Bookstore{% endblock title %}</title>

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">

  <link rel="icon" href="{% static 'img/book_icon.png' %}">
  <!-- Material Design -->
  <link href='//fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/material.min.css" %}">
  <!-- Bootstrap -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static "css/mdstyles.css" %}">

</head>

<body>

  {% include "includes/nav_bookstore.html" %}

<div class="container">
  {% block content %}{% endblock content %}
</div>

  <script src="https://code.getmdl.io/1.1.3/material.min.js"></script>
</body>
</html>

djexperience/core/templates/base_bookstore_nav.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Introducing Lollipop, a sweet new take on Android.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <title>{% block title %}Bookstore{% endblock title %}</title>

  <!-- Page styles -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" type='text/css'>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="{% static "css/material.min.css" %}">
  <link rel="stylesheet" href="{% static "css/mdstyles.css" %}">
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}">

  <style>
    .intro {
      padding-top: 60px;
    }

    #view-source {
      position: fixed;
      display: block;
      right: 0;
      bottom: 0;
      margin-right: 40px;
      margin-bottom: 40px;
      z-index: 900;
    }
  </style>

</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  {% include "includes/nav_bookstore.html" %}
  <div class="android-content mdl-layout__content">
    <a name="top"></a>
{#    <div class="android-screen-section mdl-typography--text-center">#}
{#      <a name="screens"></a>#}
{#    </div>#}
    <div class="intro container">
      {% block content %}{% endblock content %}
    </div>
  </div>
</div>

<script src="https://code.getmdl.io/1.1.3/material.min.js"></script>
</body>
</html>

djexperience/core/templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Django Experience{% endblock title %}</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

    <!-- dataTables css -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>

    {% block css %}{% endblock css %}

    <style>
      #page-top {
        padding-top: 10px;
      }
    </style>

</head>

<body id="page-top">

    <div class="container">
      {% block content %}{% endblock content %}
    </div>


    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <script src="{% static "js/jquery.fittext.js" %}"></script>
    <script src="{% static "js/wow.min.js" %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/creative.js" %}"></script>

    <!-- dataTables.min.js -->
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    {% block js %}{% endblock js %}
</body>

</html>

djexperience/core/templates/base_crm_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  {% block title %}
    <title>CRM|</title>
  {% endblock title %}

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css">
  <link rel="stylesheet" href="{% static "css/mystyle.css" %}">

  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/semantic.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/site.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/container.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/image.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/menu.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/divider.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/segment.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/dropdown.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/icon.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/table.css' %}">
  <!-- My personal semantic CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic/mysemantic_lists.css' %}">

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <!-- dataTables -->
  <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>

</head>
<body>

{% block menu %}
  <div class="ui fixed inverted menu">
    <div class="ui container">
      <a href="{% url 'core:home' %}" class="header item">
        <img class="logo" src="{% static 'img/semantic/logo.png' %}">
        Django Experience
      </a>
      <a href="{% url 'crm:crm_index' %}" class="item">Home</a>
      <div class="ui simple dropdown item">
        Listas <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item" href="{% url 'crm:customer_list' %}">Clientes</a>
          <a class="item" href="{% url 'crm:provider_list' %}">Fornecedores</a>
          <a class="item" href="{% url 'crm:seller_list' %}">Vendedores</a>
          <a class="item" href="{% url 'crm:employee_list' %}">Funcionários</a>
        </div>
      </div>
    </div>
  </div>
{% endblock menu %}

{% block content %}{% endblock content %}

{% block footer %}
  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Sitemap</a>
            <a href="#" class="item">Contact Us</a>
            <a href="#" class="item">Religious Ceremonies</a>
            <a href="#" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Services</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Banana Pre-Order</a>
            <a href="#" class="item">DNA FAQ</a>
            <a href="#" class="item">How To Access</a>
            <a href="#" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Django Experience | CRM 2016</h4>
          <p>Este template foi feito com <a href="http://semantic-ui.com/" target="_blank">semantic-ui</a>.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock footer %}

</body>

</html>

djexperience/core/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Django Experience</h1>
                <hr>
                <p>Django Experience é um projeto escrito em Django.</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Leia mais</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Django Experience</h2>
                    <hr class="light">
                    <p class="text-faded">O projeto é open source, e você pode baixá-lo gratuitamente.</p>
                    <a target="_blank" href="https://github.com/rg3915/django-experience" class="btn btn-default btn-xl">Baixe aqui</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Serviços</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'bookstore:bookstore_index' %}"><i class="fa fa-4x fa-book wow bounceIn text-primary"></i></a>
                        <h3><a href="{% url 'bookstore:bookstore_index' %}">Livraria</a></h3>
                        <p class="text-muted">Exemplo de uma aplicação de uma Livraria.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'crm:crm_index' %}"><i class="fa fa-4x fa-users wow bounceIn text-primary" data-wow-delay=".1s"></i></a>
                        <h3><a href="{% url 'crm:crm_index' %}">CRM</a></h3>
                        <p class="text-muted">Gerenciamento de pessoas.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-tags wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>Produtos</h3>
                        <p class="text-muted">Catálogo de produtos.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-shopping-cart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                        <h3>Vendas</h3>
                        <p class="text-muted">Gerenciamento de vendas.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static "img/portfolio/1.jpg" %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static "img/portfolio/2.jpg" %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static "img/portfolio/3.jpg" %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static "img/portfolio/4.jpg" %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static "img/portfolio/5.jpg" %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static "img/portfolio/6.jpg" %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
            </div>
        </div>
    </aside> -->

    <!-- <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
                </div>
            </div>
        </div>
    </section> -->
{% endblock content %}